query training (
  $id: String!
) {
  training (
    id: $id
  ) {
    title
    request
    noMatch
    unknownSuggestion
    userSays {
      actionStatus
      type
      intentResult {
        id
        title
      }
      text
      entityRanges {
        offset
        length
        paramKey
      }
      params {
        name
        entity {
          id
          title
        }
        key
      }
    }
  }
}