mutation updateIntegration (
  $id: String!
  $vendor: String!
  $setting: String
) {
  updateIntegration (
    id: $id
    vendor: $vendor
    setting: $setting
    type: "nlp"
  ) {
    id
    vendor
    setting
  }
}