mutation updateWebhookProject (
  $id: String!
  $webhookUrl: String
  $webhookUsername: String
  $webhookAvailable: Boolean
  $gatewayUrl: String
  $basicAuthUsername: String
  $basicAuthPassword: String
) {
  updateWebhookProject (
    id: $id
    webhookUrl: $webhookUrl
    webhookUsername: $webhookUsername
    webhookAvailable: $webhookAvailable
    gatewayUrl: $gatewayUrl
    basicAuthUsername: $basicAuthUsername
    basicAuthPassword: $basicAuthPassword
  ) {
    id
    webhookUrl
    webhookUsername
    webhookAvailable
    gatewayUrl
    basicAuthUsername
    basicAuthPassword
  }
}