mutation createIntent (
  $title: String!
  $projectId: String!
  $values: [String!]
) {
  createIntent (
    title: $title
    values: $values
    projectId: $projectId
  ) {
    id
    title
    values
  }
}