query intent (
  $id: String!
) {
  intent (
    id: $id
  ) {
    title
    values {
      text
      entityRanges {
        offset
        length
        entity {
          id
          title
        }
      }
    }
    params {
      name
      entity {
        id
        title
      }
    }
  }
}