mutation updateIntent (
  $id: String!
  $title: String
  $values: [IntentValueInput!]
  $params: [IntentParamInput!]
) {
  updateIntent (
    id: $id
    title: $title
    values: $values
    params: $params
  ) {
    title
    values {
      text
      entityRanges {
        offset
        length
        paramKey
      }
    }
    params {
      name
      entity {
        id
        title
      }
      key
    }
  }
}