mutation updateIntent (
  $id: String!
  $title: String
  $values: [IntentValueInput!]
  $params: [IntentParamInput!]
) {
  updateIntent (
    id: $id
    title: $title
    values: $values
  ) {
    title
    values {
      text
      entityRanges {
        offset
        length
        entity {
          id
          title
        }
      }
    }
    params {
      name
      entity {
        id
        title
      }
    }
  }
}