mutation updateProject (
  $id: String!
  $title: String!
  $description: String
  $timeZone: String
  $language: String
) {
  updateProject (
    id: $id
    title: $title
    description: $description
    timeZone: $timeZone
    language: $language
  ) {
    id
    title
    description
    timeZone
    language
  }
}