query dialog (
  $id: String!
) {
  dialog (
    id: $id
  ) {
    title
    messages {
      id
      parentId
      type
      title
      actionName
      intent {
        id
        title
        values {
          text
        }
      }
      params {
        name
        required
        prompts
      }
      payload {
        type
        platform
        value
      }
      depth
    }
  }
}