mutation updateDialog (
  $id: String!
  $title: String
  $messages: [MessageInput!]
) {
  updateDialog (
    id: $id
    title: $title
    messages: $messages
  ) {
    id
    title
    messages {
      id
      parentId
      type
      title
      actionName
      webhookUsed
      intent {
        id
        title
        values {
          text
        }
      }
      params {
        name
        required
        prompts
      }
      payload {
        type
        platform
        value
      }
    }
  }
}