mutation updateDialog (
  $id: String!
  $title: String
  $rootMessageId: String
  $messages: [MessageInput!]
) {
  updateDialog (
    id: $id
    title: $title
    rootMessageId: $rootMessageId
    messages: $messages
  ) {
    id
    title
    messages
  }
}