query myIntegrationsByIdNoAuth (
  $projectId: String!
) {
  myIntegrationsByIdNoAuth (
    projectId: $projectId
    type: "nlp"
  ) {
    qiscusAccountEmail
    qiscusAccountPassword
    qiscusAppId
    secretKeyBot
    senderEmail
  }
}