mutation detectIntent (
  $id: String!
  $sessionTag: String!
  $utterance: String!
  $contexts: [ContextInput!]!
) {
  detectIntent(
    id: $id
    sessionTag: $sessionTag
    utterance: $utterance
    contexts: $contexts
  ) {
    messageName
    dialogName
    response
    contexts {
      name
      lifespanCount
      parameters {
        name
        value
      }
    }
    parameters {
      name
      value
    }
  }
}