query myTrainings (
  $projectId: String!
  $filters: [Filter!]
  $limit: Int
  $offset: Int
  $keyword: String
) {
  myTrainings (
    projectId: $projectId
    limit: $limit
    offset: $offset
    keyword: $keyword
    filters: $filters
  ) {
    trainings {
    	id
      title
      request
      noMatch
      startQueryTime
    }
    pageInfo {
      total
    }
  }
}